/* Noura Skin Secrets — full treatment catalog, transcribed from Behandlingskatalog PDF */

const TREATMENT_CATEGORIES = [
  {
    id: "ansikte",
    name: "Ansiktsbehandlingar",
    icon: "✨",
    treatments: [
      { name: "Klassisk ansiktsrengöring", duration: "45 min", price: "1 195 kr", desc: "Djuprengörande behandling för alla hudtyper. Rengöring, peeling, ånga, portömning, ansiktsmassage och avslutande mask." },
      { name: "Diamond Microdermabrasion (Diamantpeeling)", duration: "60 min", price: "800 kr", desc: "Mekanisk peeling som avlägsnar döda hudceller och förnyar hudytan skonsamt men effektivt." },
      { name: "Kemisk peeling", duration: "60 min", price: "1 500 kr", desc: "Professionell kemisk peeling som förnyar huden, minskar ojämnheter och förbättrar hudstrukturen." },
      { name: "Oxygen Ansiktsbehandling", duration: "75–90 min", price: "1 500 kr", desc: "Komplett djuprengöring: ånga, kemisk peeling, scrubber, pordjuprengöring, diamant- och oxygenpeeling, lermask, sheet mask och LED-mask." },
      { name: "Ansiktsbehandling (HydraFacial)", duration: "60 min", price: "1 900 kr", desc: "Rengör på djupet, avlägsnar pormaskar och återfuktar med aktiva serum. Direkt lyster, ingen återhämtningstid." },
      { name: "Avancerad ansiktsrengöring – HydraFacial, Diamantslipning & Microneedling (15 in 1)", duration: "90 min", price: "2 000 kr", desc: "Djuprengörande HydraFacial, diamantpeeling och microneedling för fastare, klarare och friskare hud." },
      { name: "Lyx Ansiktsbehandling – Microneedling + HydraFacial", duration: "90 min", price: "2 200 kr", desc: "Ånga, rengöring, vattenpeeling, diamantpeeling, ultraljud, RF, lermask, sheet mask, LED-mask samt microneedling med Vitamin C och hyaluronsyra." },
      { name: "VIP Terapi – Glöd & Kollagenboost", duration: "90 min", price: "1 800 kr", desc: "Rengöring, oxygenpeeling, ultraljud, microneedling med vitamincocktail, RF, högfrekvens och LED-mask – blått och rött ljus." },
      { name: "BB-Glow", duration: "45–60 min", price: "1 800 kr", desc: "Microneedling med pigmentberikade serum för jämnare hudton, lyster och lätt täckning – som BB-kräm fast inifrån.", note: "Rekommenderas som kur: 3–5 behandlingar." },
      { name: "Cold Plasma", duration: "60 min", price: "1 500 kr", desc: "Smärtfri behandling som rengör och desinficerar på djupet, minskar bakterier och lugnar inflammation. Perfekt för akne och stora porer." },
      { name: "Mesoterapi för ansiktet", duration: "60 min", price: "1 400 kr", desc: "Djupgående mesoterapi som tillför näring, vitaminer och hyaluronsyra direkt till huden." },
      { name: "Microneedling – valfri aktiv lösning", duration: "60 min", price: "900 kr", desc: "Skräddarsydd microneedling efter ditt hudbehov: hudförnyelse (DNA Salmon), hudblekning (Glutathion + C-vitamin), uppstramning (Botopeptider + Kollagen), pigmentfläckar (Tranexamsyra + Kojicsyra), ärr (Centella-extrakt), ålderstecken (Zink + HA), återfuktning (Hyaluronsyra 3%) eller djupnäring (Mannitol + Lipogrow)." },
      { name: "DNA Salmon – Ansiktsbehandling", duration: "45 min", price: "1 200 kr", desc: "Microneedling med DNA Salmon för cellförnyelse och kollagenstimulering. Minskar porstorlek och ger lyster. Inkluderar peeling, bedövning, ultraljud och LED." },
      { name: "Lyxig ansiktsbehandling med DNA Salmon", duration: "60 min", price: "995 kr", desc: "Djuprengöring, diamantslipning, organisk lermask, microneedling med DNA Salmon, sheetmask med ultraljud och LED-mask." },
      { name: "Microneedling – Ansikte, hals & dekolletage", duration: "60 min", price: "1 500 kr", desc: "Fullständig microneedlingbehandling med djuprengöring för ansikte, hals och dekolletage." },
      { name: "REVITALIFTPRO 20 + Mesojun – Återfuktning & Fasthet", duration: "50–60 min", price: "1 500 kr", desc: "Hyaluronsyra i tre molekylvikter, peptider, vitaminer och DMAE. Revitaliserar, återfuktar och ger huden fasthet och ungdomlig lyster." },
      { name: "Vitamin C Glow Facial", duration: "60 min", price: "1 300 kr", desc: "Vitamin C-behandling som ger lyster, jämnar ut hudtonen och minskar pigmentering. Perfekt för trött, glåmig hud." },
      { name: "FIRMPRO + Mesojun – Ansiktslyft & Fasthet", duration: "50–60 min", price: "1 500 kr", desc: "DMAE, Organiskt Silanol, Panthenol och hyaluronsyra som definierar ansiktsoval, lyfter och motverkar slapphet." },
      { name: "COLLAGEN-HA PRO + Mesojun – Anti-Aging & Återfuktning", duration: "50–60 min", price: "1 500 kr", desc: "Marint kollagen och hyaluronsyra med Succinic Acid mot ålderstecken, för bättre elasticitet och djup återfuktning." },
      { name: "B-LEUA RELAX – Naturligt alternativ till botox", duration: "60 min", price: "1 800 kr", desc: "Naturlig uppstramning som minskar mimiska linjer utan att frysa ansiktsuttrycken. Stimulerar kollagen och elastin. 100% säker, ingen återhämtning." },
      { name: "Mesojun + Hyaluronsyra 3% + Microneedling – Fukt & Anti-Aging", duration: "50–60 min", price: "1 800 kr", desc: "150 mg hyaluronsyra i tre molekylvikter med microneedling för djup återfuktning och minskade fina linjer." },
      { name: "Microneedling + TRANEX PRO – Hudtonsbalans & Lyster", duration: "50–60 min", price: "1 000 kr", desc: "Tranexamic Acid, Kojic Acid och C-vitamin med microneedling för jämnare hudton och reducerade pigmentfläckar." },
      { name: "Mesojun + TRANEX PRO + Microneedling – Hudtonsbalans & Lyster", duration: "50–60 min", price: "1 800 kr", desc: "Förstärkt version av ovanstående med Mesojun för djupare hudföryngring och starkare effekt på pigmentfläckar." },
      { name: "BRIGHTPRO + Mesojun + Microneedling – Revitalisering & Ljusare hud", duration: "50–60 min", price: "1 800 kr", desc: "Högkoncentrerat Glutathion med C-vitamin och hyaluronsyra. Ger strålande, jämnare hudton och stimulerar kollagen." },
      { name: "BOOSTER PRO EXOSOMER – Glöd & Revitaliserad hud", duration: "45–55 min", price: "1 500 kr", desc: "Djuprengöring och intensiv återfuktning med exosomer för maximal lyster, föryngring och jämn hudton." },
      { name: "Mesojun + BIOPLAX PRO + Microneedling – DNA-Revitalisering", duration: "50–60 min", price: "2 000 kr", desc: "DNA extraherat från laxrom med 13 vitaminer, 20 aminosyror och peptider. Djupgående revitalisering på cellnivå." },
    ],
  },
  {
    id: "hifu-ansikte",
    name: "HIFU – Ansikte",
    icon: "🌟",
    treatments: [
      { name: "VMAX HIFU & RF – Hela ansiktet", duration: "60 min", price: "1 999 kr", desc: "Senaste generationens hudföryngring. Stimulerar kollagenproduktionen upp till 4 gånger mer. Inga nålar, ingen smärta. Resultat 1–2 år." },
      { name: "HIFU – Hela ansiktet", duration: "60 min", price: "3 500 kr", desc: "Djupverkande fokuserat ultraljud som minskar rynkor, lyfter och ger naturlig lyster. Mild värme, ingen kirurgi." },
      { name: "HIFU – Runt ögonen", duration: "20 min", price: "1 200 kr", desc: "Skonsam HIFU för det känsliga ögonpartiet. Minskar fina linjer och ger spänst." },
      { name: "HIFU för ansikte", duration: "90 min", price: "1 800 kr", desc: "Djupverkande behandling som stimulerar kollagenproduktionen och ger ansiktet ett naturligt lyft." },
    ],
  },
  {
    id: "ogon-lappar",
    name: "Ögon & Läppar",
    icon: "👁",
    treatments: [
      { name: "Mesoterapi Eye Lift – Kollagenboost", duration: "45 min", price: "799 kr", desc: "Microneedling och mesoterapi runt ögonen med serum som imiterar botoxeffekten. Minskar fina linjer, påsar och mörka ringar.", note: "Rekommenderas som kur: 3–4 behandlingar." },
      { name: "Pigmentbehandling för ögonpartiet", duration: "30 min", price: "900 kr", desc: "Mot pigmentfläckar, melasma och mörka ringar. Peeling, pigmenthämmande mask, C-vitaminserum och solskydd." },
      { name: "HIFU Ögonbehandling – Icke-kirurgiskt lyft", duration: "30 min", price: "1 200 kr", desc: "Fokuserat ultraljud som lyfter och stramar upp huden runt ögonen utan nålar. Ingen återhämtningstid.", note: "Rekommenderas var 6:e månad." },
      { name: "PlasmaJet för ögonlyft med ultraljud och RF", duration: "60 min", price: "2 000 kr", desc: "Nålfri behandling mot hängande ögonlock, kråksparkar och slapp hud. Stimulerar naturlig kollagenproduktion." },
      { name: "BB-Lips med Tint – Färg, fukt & glow", duration: "60 min", price: "700 kr", desc: "Microneedling med serum rikt på hyaluronsyra och naturliga pigment. Jämnar ut läpparnas färg, naturlig tint-effekt utan smink.", note: "Kur: 2–4 behandlingar." },
      { name: "Microneedling Lips med Mesoterapi", duration: "45 min", price: "800 kr", desc: "Återfuktar och förbättrar läpparnas struktur och färg med microneedling och mesoterapiserum. Utan fillers." },
      { name: "LIPS SHINE PRO – Volym & Lyster", duration: "30–40 min", price: "1 000 kr", desc: "Hyaluronsyra och aktiva peptider för ökad volym, mjukare linjer runt munnen och naturlig färg med Ginkgo Biloba." },
      { name: "HydraLips – Lyxbehandling", duration: "60 min", price: "1 200 kr", desc: "Fysisk + kemisk peeling, HydraNeedling, mesoterapi med hyaluronsyra och vitaminer, lugnande mask och återfuktande balm." },
    ],
  },
  {
    id: "harvard",
    name: "Hårvård",
    icon: "💇‍♀️",
    treatments: [
      { name: "Hår Microneedling (Mesoterapi)", duration: "60 min", price: "1 000 kr", desc: "Stärker hårsäckarna och stimulerar ny hårväxt med microneedling, exosomer, high frequency och LED-terapi." },
      { name: "Mesojun + HAIRPRO Exosomes – Hårrevitalisering", duration: "40–50 min", price: "1 000 kr", desc: "5,49 miljoner stabila exosomer med Ginkgo Biloba och peptider. Stimulerar hårbotten, motverkar håravfall." },
      { name: "Lyxig hår- och hårbottenbehandling", duration: "60 min", price: "1 800 kr", desc: "Hydro-dermabrasion, DNA Salmon-spray, exosomer, hyaluronsyra, radiofrekvens och högfrekvenskam för friskare hårväxt." },
    ],
  },
  {
    id: "massage-ansikte",
    name: "Massage – Ansikte",
    icon: "🤍",
    note: "Endast för kvinnor",
    treatments: [
      { name: "Ansiktsmassage", duration: "30 min", price: "700 kr", desc: "Mjuk, rogivande massage fokuserad på ansiktet. Löser spänningar och hjälper mot spänningshuvudvärk.", note: "Endast för kvinnor." },
      { name: "Ansiktsmassage / Akupressurmassage", duration: "30 min", price: "850 kr", desc: "Djupgående fasciamassage med lyftande och cirkulationsökande tekniker, anpassad efter behov.", note: "Endast för kvinnor." },
      { name: "Ansikts- & Nackmassage", duration: "60 min", price: "1 500 kr", desc: "Ansikts- och nackmassage med massage av dekolletage, axlar, armar och händer. Stramar upp och löser djupa spänningar.", note: "Endast för kvinnor." },
      { name: "Ansikts-, Skalp- & Dekolletagemassage", duration: "30 min", price: "700 kr", desc: "Klassisk massage av ansikte, skalp, nacke och dekolletage. Energigivande paus under dagen.", note: "Endast för kvinnor. Kur 3 behandlingar: 1 450 kr." },
      { name: "Ansikts-, Skalp- & Dekolletagemassage – Paket 5 behandlingar", duration: "120 min/tillfälle", price: "1 950 kr", desc: "Total avslappning med omsorgsfull massage av ansikte, skalp, nacke och dekolletage.", note: "Endast för kvinnor." },
      { name: "Ansiktsbehandling inkl. 15 min ryggmassage", duration: "30 min", price: "1 299 kr", desc: "Ryggmassage mot spända muskler med NBE-maskin, följt av grundläggande ansiktsbehandling med hudanalys, peeling och serum.", note: "Tillval (portömning, fransfärg m.m.) anges vid bokning." },
    ],
  },
  {
    id: "massage-kropp",
    name: "Massage – Kropp",
    icon: "💆‍♀️",
    treatments: [
      { name: "Avslappningsmassage", duration: "30 min", price: "från 900 kr", desc: "Skonsam, lugnande massage för hela kroppen." },
      { name: "Klassisk svensk massage", duration: "30 min", price: "1 000 kr", desc: "Traditionell svensk massageteknik mot spänningar i kroppen." },
      { name: "Rygg & Nacke", duration: "30 min", price: "999 kr", desc: "Fokuserad massage på rygg och nacke." },
      { name: "Ryggmassage med radiofrekvens (NBE 3000)", duration: "30 min", price: "999 kr", desc: "20 min med NBE 3000-maskin som löser upp spända vävnader och myoser, följt av 10 min handmassage." },
      { name: "Dekolletémassage", duration: "20 min", price: "700 kr", desc: "Riktad massage för dekolletageområdet." },
      { name: "Lätt lymfmassage", duration: "30 min", price: "1 100 kr", desc: "Skonsam lymfdränerande massage som minskar svullnad och stimulerar cirkulationen." },
      { name: "Helkroppsmassage", duration: "45 min", price: "1 800 kr", desc: "Komplett massage för hela kroppen." },
    ],
  },
  {
    id: "kroppsbehandlingar",
    name: "Kroppsbehandlingar",
    icon: "🧴",
    treatments: [
      { name: "Ryggbehandling mot akne", duration: "60 min", price: "1 000 kr", desc: "Antibakteriell rengöring, kemisk peeling, diamantslipning, oxygenbehandling och lermask. Lugnar inflammationer." },
      { name: "Behandling för knän", duration: "45 min", price: "1 000 kr", desc: "Rengöring, peeling, diamantslipning, oxygenbehandling och mask för mörka eller ojämna knän." },
      { name: "Behandling för ben – lyster & jämnare hudton", duration: "60 min", price: "1 000 kr", desc: "Exfoliering, återfuktning och hudtonsutjämning för benens hud." },
      { name: "Behandling för armhålor", duration: "45 min", price: "1 000 kr", desc: "Lugnar och ljusar upp mörka eller irriterade armhålor." },
      { name: "Behandling för armar och händer", duration: "45 min", price: "1 000 kr", desc: "Skonsam behandling för torra, mörka eller fläckiga armar och händer." },
      { name: "Lyxbehandling för händer – Microneedling & Mesoterapi", duration: "60 min", price: "1 200 kr", desc: "Peeling, diamantslipning, oxygenbehandling, microneedling och mesoterapi (Kollagen + DNA Salmon). Synlig glow." },
    ],
  },
  {
    id: "slim-firm",
    name: "Slim & Firm – Kroppsformning",
    icon: "🔥",
    treatments: [
      { name: "Mesoterapi för magen", duration: "60 min", price: "2 000 kr", desc: "Förbättrar hudens fasthet och minskar fettansamlingar med microneedling, mesoterapi, ultraljud och RF." },
      { name: "Mesoterapi för midja & höfter (love handles)", duration: "60 min", price: "2 500 kr", desc: "Formar midjan och reducerar fettdepåer på sidorna med fettbrytande serum och lymfdränerande massage." },
      { name: "Mesoterapi för rumpa & lår", duration: "60 min", price: "2 500 kr", desc: "Minskar celluliter och förbättrar hudens spänst med microneedling, mesoterapi, ultraljud och RF." },
      { name: "Mesoterapi för armar (överarmar)", duration: "45–60 min", price: "2 000 kr", desc: "Reducerar fett och slapp hud på överarmarna med fettlösande mesoterapi och RF." },
      { name: "Mesoterapi för dubbelhaka och käklinje", duration: "45 min", price: "1 500 kr", desc: "Minskar fett under hakan och stramar upp huden med fettlösande mesoterapi, RF och lätt massage." },
    ],
  },
  {
    id: "bristningar",
    name: "Bristningsbehandling",
    icon: "🌿",
    treatments: [
      { name: "Mesoterapi mot bristningar – Mage", duration: "60 min", price: "1 099 kr", desc: "Minskar synligheten av bristningar på magen, särskilt efter graviditet eller viktförändringar." },
      { name: "Mesoterapi mot bristningar – Höfter & Lår", duration: "60 min", price: "1 099 kr", desc: "Minskar bristningar och förbättrar hudens ton, struktur och fasthet på höfter och lår." },
      { name: "Mesoterapi mot bristningar – Armar", duration: "45 min", price: "1 099 kr", desc: "Förbättrar hudstrukturen och reducerar bristningar på överarmarna." },
      { name: "Mesoterapi mot bristningar – Bröstområde", duration: "45 min", price: "1 099 kr", desc: "Skonsam behandling för bristningar på bröstet, särskilt efter amning eller viktförändringar." },
      { name: "Laser – Stretch Marks (Mage)", duration: "45 min", price: "1 800 kr", desc: "Laserbehandling som stimulerar kollagenproduktionen. Passar både nya (röda) och äldre (vita) bristningar." },
    ],
  },
  {
    id: "hifu-kropp",
    name: "HIFU – Kropp",
    icon: "💫",
    treatments: [
      { name: "HIFU – Haklinje (dubbelhaka)", duration: "30 min", price: "1 500 kr", desc: "Stramar upp huden under hakan och minskar dubbelhaka." },
      { name: "HIFU – Dekolletage", duration: "40 min", price: "2 000 kr", desc: "Förbättrar hudens fasthet och struktur i bröstområdet." },
      { name: "HIFU – Armar (överarmar)", duration: "30 min", price: "2 500 kr", desc: "Stärker huden på överarmarna och reducerar slapphet." },
      { name: "HIFU – Lår", duration: "45 min", price: "2 500 kr", desc: "Stramar upp huden på låren och reducerar slapphet." },
      { name: "HIFU – Mage", duration: "45 min", price: "2 500 kr", desc: "Stramar upp huden på magen, särskilt efter viktminskning eller graviditet." },
    ],
  },
  {
    id: "laser",
    name: "Laser",
    icon: "⚡",
    treatments: [
      { name: "Pico Laser + Djupgående rengöring & peeling", duration: "60–75 min", price: "2 000 kr", desc: "HydraFacial/Oxygeneo + Diamond Peel för rengöring, följt av Pico Laser mot pigmentering, ytliga ärr och kollagenstimulering." },
      { name: "Laser Carbon + HydraFacial + Lugnande mask", duration: "60 min", price: "2 000 kr", desc: "Laser Carbon djuprengör porer och minskar pigmentering. HydraFacial återfuktar. Perfekt för fet hud och stora porer." },
      { name: "Laser – Borttagning av tatuering", duration: "20–40 min", price: "från 800 kr", desc: "Lasern bryter ner bläckpartiklarna gradvis. Antal behandlingar varierar med storlek, placering och färg." },
      { name: "Laser – Borttagning av tatuering (läppar/ögonbryn)", duration: "15–30 min", price: "800 kr", desc: "Specialiserad, precis behandling för känsliga områden. Gradvis och naturlig blekning." },
    ],
  },
  {
    id: "plasma",
    name: "Plasma",
    icon: "🩵",
    treatments: [
      { name: "Plasma Radiance – Full Facial Treatment", duration: "65 min", price: "1 200 kr", desc: "Rengöring, PlasmaPen med vitaminserum (BSK29), LED-ljusterapi och återfuktande mask. Lyster utan irritation.", note: "Upprepas var 3–4 vecka." },
      { name: "PlasmaJet – Hela ansiktet", duration: "60 min", price: "3 000 kr", desc: "Mikroskopiska punkter som stimulerar naturlig kollagenproduktion och ger ett synligt lyft." },
      { name: "Borttagning av skin tags med Plasma Pen", duration: "15–30 min", price: "från 1 500 kr", desc: "Nålfri borttagning av hudutväxter (fibrom) på hals, ansikte, armhålor eller kropp.", note: "Konsultation krävs innan bokning." },
    ],
  },
  {
    id: "arrbehandling",
    name: "Ärrbehandling",
    icon: "🌸",
    treatments: [
      { name: "SCARPRO + Mesojun – Hudreparation", duration: "50–60 min", price: "1 500 kr", desc: "Stimulerar hudförnyelse, förbättrar hudstruktur och minskar synligheten av akneärr." },
      { name: "SCARPRO + Mesojun + Microneedling – Komplett ärrbehandling", duration: "60–70 min", price: "1 800 kr", desc: "Djupare behandling med microneedling för starkare kollagenstimulering och bättre ärrminskning." },
      { name: "Algpeeling", duration: "45 min", price: "1 800 kr", desc: "Naturlig peeling med mikroskopiska algspikler som aktiverar cellförnyelse. Förfinade porer, förbättrade akneärr." },
    ],
  },
  {
    id: "ovrigt",
    name: "Övrigt",
    icon: "🕊",
    treatments: [
      { name: "Hudvårdskonsultation", duration: "20 min", price: "450 kr", desc: "Personlig hudanalys för att hitta rätt behandling för din hudtyp." },
    ],
  },
];
