/* Noura Skin Secrets — behandlingskatalog (SV/EN/AR)
   Bakåtkompatibel: name/desc = svenska (används av hudassistent.js).
   nameEn/nameAr/descEn/descAr används av katalog-renderaren per språk. */

const TREATMENT_CATEGORIES = [
{
  id: "ansikte",
  name: "Ansiktsbehandlingar",
  nameEn: "Facial treatments",
  nameAr: "علاجات الوجه",
  icon: "✨",
  treatments: [
    { name: "Klassisk ansiktsrengöring", nameEn: "Classic deep-cleansing facial", nameAr: "تنظيف البشرة الكلاسيكي العميق",
      duration: "45 min", price: "1 195 kr",
      desc: "Djuprengörande behandling för alla hudtyper. Rengöring, peeling, ånga, portömning, ansiktsmassage och avslutande mask.",
      descEn: "Deep-cleansing treatment for all skin types. Cleansing, peeling, steam, pore extraction, facial massage and a finishing mask.",
      descAr: "علاج تنظيف عميق لجميع أنواع البشرة: تنظيف، تقشير، بخار، تنظيف المسام، مساج للوجه وقناع ختامي." },
    { name: "Diamond Microdermabrasion (Diamantpeeling)", nameEn: "Diamond microdermabrasion", nameAr: "التقشير الماسي (ميكروديرمابريجن)",
      duration: "60 min", price: "800 kr",
      desc: "Mekanisk peeling som avlägsnar döda hudceller och förnyar hudytan skonsamt men effektivt.",
      descEn: "Mechanical peeling that removes dead skin cells and renews the skin surface — gentle yet effective.",
      descAr: "تقشير ميكانيكي يزيل خلايا الجلد الميتة ويجدد سطح البشرة بلطف وفعالية." },
    { name: "Kemisk peeling", nameEn: "Chemical peel", nameAr: "التقشير الكيميائي",
      duration: "60 min", price: "1 500 kr",
      desc: "Professionell kemisk peeling som förnyar huden, minskar ojämnheter och förbättrar hudstrukturen.",
      descEn: "Professional chemical peel that renews the skin, reduces unevenness and improves skin texture.",
      descAr: "تقشير كيميائي احترافي يجدد البشرة ويقلل التصبغات ويحسّن ملمس الجلد." },
    { name: "Oxygen Ansiktsbehandling", nameEn: "Oxygen facial", nameAr: "علاج الوجه بالأوكسجين",
      duration: "75–90 min", price: "1 500 kr",
      desc: "Komplett djuprengöring: ånga, kemisk peeling, scrubber, pordjuprengöring, diamant- och oxygenpeeling, lermask, sheet mask och LED-mask.",
      descEn: "Complete deep cleanse: steam, chemical peel, skin scrubber, deep pore cleansing, diamond and oxygen peeling, clay mask, sheet mask and LED mask.",
      descAr: "تنظيف عميق متكامل: بخار، تقشير كيميائي، سكرابر، تنظيف عميق للمسام، تقشير ماسي وأوكسجين، قناع طيني، شيت ماسك وقناع LED." },
    { name: "Ansiktsbehandling (HydraFacial)", nameEn: "HydraFacial", nameAr: "هيدرافيشل",
      duration: "60 min", price: "1 900 kr",
      desc: "Rengör på djupet, avlägsnar pormaskar och återfuktar med aktiva serum. Direkt lyster, ingen återhämtningstid.",
      descEn: "Cleanses deeply, removes blackheads and hydrates with active serums. Instant glow, no downtime.",
      descAr: "ينظف بعمق، يزيل الرؤوس السوداء ويرطب بسيرومات فعالة. إشراقة فورية بدون فترة تعافٍ." },
    { name: "Avancerad ansiktsrengöring – HydraFacial, Diamantslipning & Microneedling (15 in 1)", nameEn: "Advanced facial – HydraFacial, diamond peel & microneedling (15 in 1)", nameAr: "تنظيف متقدم – هيدرافيشل، تقشير ماسي وميكرونيدلينغ (15 في 1)",
      duration: "90 min", price: "2 000 kr",
      desc: "Djuprengörande HydraFacial, diamantpeeling och microneedling för fastare, klarare och friskare hud.",
      descEn: "Deep-cleansing HydraFacial, diamond peeling and microneedling for firmer, clearer, healthier skin.",
      descAr: "هيدرافيشل منظف بعمق مع تقشير ماسي وميكرونيدلينغ لبشرة مشدودة وأصفى وأكثر صحة." },
    { name: "Lyx Ansiktsbehandling – Microneedling + HydraFacial", nameEn: "Luxury facial – microneedling + HydraFacial", nameAr: "علاج الوجه الفاخر – ميكرونيدلينغ + هيدرافيشل",
      duration: "90 min", price: "2 200 kr",
      desc: "Ånga, rengöring, vattenpeeling, diamantpeeling, ultraljud, RF, lermask, sheet mask, LED-mask samt microneedling med Vitamin C och hyaluronsyra.",
      descEn: "Steam, cleansing, aqua peeling, diamond peeling, ultrasound, RF, clay mask, sheet mask, LED mask plus microneedling with vitamin C and hyaluronic acid.",
      descAr: "بخار، تنظيف، تقشير مائي وماسي، موجات فوق صوتية، RF، قناع طيني، شيت ماسك، قناع LED مع ميكرونيدلينغ بفيتامين C وحمض الهيالورونيك." },
    { name: "VIP Terapi – Glöd & Kollagenboost", nameEn: "VIP therapy – glow & collagen boost", nameAr: "علاج VIP – توهج وتعزيز الكولاجين",
      duration: "90 min", price: "1 800 kr",
      desc: "Rengöring, oxygenpeeling, ultraljud, microneedling med vitamincocktail, RF, högfrekvens och LED-mask – blått och rött ljus.",
      descEn: "Cleansing, oxygen peeling, ultrasound, microneedling with a vitamin cocktail, RF, high frequency and LED mask — blue and red light.",
      descAr: "تنظيف، تقشير بالأوكسجين، موجات فوق صوتية، ميكرونيدلينغ بكوكتيل فيتامينات، RF، تردد عالٍ وقناع LED بالضوء الأزرق والأحمر." },
    { name: "BB-Glow", nameEn: "BB-Glow", nameAr: "بي بي جلو",
      duration: "45–60 min", price: "1 800 kr",
      desc: "Microneedling med pigmentberikade serum för jämnare hudton, lyster och lätt täckning – som BB-kräm fast inifrån.",
      descEn: "Microneedling with pigment-enriched serums for a more even tone, glow and light coverage — like BB cream, but from within.",
      descAr: "ميكرونيدلينغ بسيرومات غنية بالصبغات لتوحيد لون البشرة وإشراقتها مع تغطية خفيفة — مثل كريم BB لكن من الداخل.",
      note: "Rekommenderas som kur: 3–5 behandlingar.", noteEn: "Recommended as a course: 3–5 sessions.", noteAr: "يُنصح به كبرنامج: 3–5 جلسات." },
    { name: "Cold Plasma", nameEn: "Cold plasma", nameAr: "البلازما الباردة",
      duration: "60 min", price: "1 500 kr",
      desc: "Smärtfri behandling som rengör och desinficerar på djupet, minskar bakterier och lugnar inflammation. Perfekt för akne och stora porer.",
      descEn: "Pain-free treatment that cleanses and disinfects deeply, reduces bacteria and calms inflammation. Ideal for acne and enlarged pores.",
      descAr: "علاج غير مؤلم ينظف ويطهر بعمق، يقلل البكتيريا ويهدئ الالتهاب. مثالي لحب الشباب والمسام الواسعة." },
    { name: "Mesoterapi för ansiktet", nameEn: "Facial mesotherapy", nameAr: "ميزوثيرابي للوجه",
      duration: "60 min", price: "1 400 kr",
      desc: "Djupgående mesoterapi som tillför näring, vitaminer och hyaluronsyra direkt till huden.",
      descEn: "Deep mesotherapy that delivers nutrients, vitamins and hyaluronic acid directly into the skin.",
      descAr: "ميزوثيرابي عميق يمد البشرة مباشرة بالمغذيات والفيتامينات وحمض الهيالورونيك." },
    { name: "Microneedling – valfri aktiv lösning", nameEn: "Microneedling – active solution of your choice", nameAr: "ميكرونيدلينغ – بمحلول فعال من اختيارك",
      duration: "60 min", price: "900 kr",
      desc: "Skräddarsydd microneedling efter ditt hudbehov: hudförnyelse (DNA Salmon), hudblekning (Glutathion + C-vitamin), uppstramning (Botopeptider + Kollagen), pigmentfläckar (Tranexamsyra + Kojicsyra), ärr (Centella-extrakt), ålderstecken (Zink + HA), återfuktning (Hyaluronsyra 3%) eller djupnäring (Mannitol + Lipogrow).",
      descEn: "Tailored microneedling for your skin's needs: renewal (DNA Salmon), brightening (glutathione + vitamin C), firming (boto-peptides + collagen), pigmentation (tranexamic + kojic acid), scars (centella extract), ageing (zinc + HA), hydration (hyaluronic acid 3%) or deep nourishment (mannitol + Lipogrow).",
      descAr: "ميكرونيدلينغ مخصص حسب حاجة بشرتك: تجديد (DNA Salmon)، تفتيح (جلوتاثيون + فيتامين C)، شدّ (ببتيدات + كولاجين)، تصبغات (حمض الترانيكساميك + الكوجيك)، ندبات (خلاصة السنتيلا)، علامات التقدم بالعمر (زنك + HA)، ترطيب (هيالورونيك 3%) أو تغذية عميقة (مانيتول + Lipogrow)." },
    { name: "DNA Salmon – Ansiktsbehandling", nameEn: "DNA Salmon facial", nameAr: "علاج الوجه DNA Salmon",
      duration: "45 min", price: "1 200 kr",
      desc: "Microneedling med DNA Salmon för cellförnyelse och kollagenstimulering. Minskar porstorlek och ger lyster. Inkluderar peeling, bedövning, ultraljud och LED.",
      descEn: "Microneedling with DNA Salmon for cell renewal and collagen stimulation. Reduces pore size and adds glow. Includes peeling, numbing, ultrasound and LED.",
      descAr: "ميكرونيدلينغ مع DNA Salmon لتجديد الخلايا وتحفيز الكولاجين. يصغّر المسام ويمنح إشراقة. يشمل تقشيراً وتخديراً وموجات فوق صوتية وLED." },
    { name: "Lyxig ansiktsbehandling med DNA Salmon", nameEn: "Luxury DNA Salmon facial", nameAr: "علاج الوجه الفاخر مع DNA Salmon",
      duration: "60 min", price: "995 kr",
      desc: "Djuprengöring, diamantslipning, organisk lermask, microneedling med DNA Salmon, sheetmask med ultraljud och LED-mask.",
      descEn: "Deep cleansing, diamond peeling, organic clay mask, microneedling with DNA Salmon, sheet mask with ultrasound and LED mask.",
      descAr: "تنظيف عميق، تقشير ماسي، قناع طيني عضوي، ميكرونيدلينغ مع DNA Salmon، شيت ماسك بالموجات فوق الصوتية وقناع LED." },
    { name: "Microneedling – Ansikte, hals & dekolletage", nameEn: "Microneedling – face, neck & décolletage", nameAr: "ميكرونيدلينغ – الوجه والرقبة والصدر",
      duration: "60 min", price: "1 500 kr",
      desc: "Fullständig microneedlingbehandling med djuprengöring för ansikte, hals och dekolletage.",
      descEn: "Complete microneedling treatment with deep cleansing for face, neck and décolletage.",
      descAr: "جلسة ميكرونيدلينغ كاملة مع تنظيف عميق للوجه والرقبة ومنطقة الصدر." },
    { name: "REVITALIFTPRO 20 + Mesojun – Återfuktning & Fasthet", nameEn: "REVITALIFTPRO 20 + Mesojun – hydration & firmness", nameAr: "REVITALIFTPRO 20 + Mesojun – ترطيب وشدّ",
      duration: "50–60 min", price: "1 500 kr",
      desc: "Hyaluronsyra i tre molekylvikter, peptider, vitaminer och DMAE. Revitaliserar, återfuktar och ger huden fasthet och ungdomlig lyster.",
      descEn: "Hyaluronic acid in three molecular weights, peptides, vitamins and DMAE. Revitalises, hydrates and restores firmness and youthful glow.",
      descAr: "حمض هيالورونيك بثلاثة أوزان جزيئية مع ببتيدات وفيتامينات وDMAE. ينشط البشرة ويرطبها ويمنحها شداً وإشراقة شبابية." },
    { name: "Vitamin C Glow Facial", nameEn: "Vitamin C glow facial", nameAr: "علاج الإشراقة بفيتامين C",
      duration: "60 min", price: "1 300 kr",
      desc: "Vitamin C-behandling som ger lyster, jämnar ut hudtonen och minskar pigmentering. Perfekt för trött, glåmig hud.",
      descEn: "Vitamin C treatment that adds radiance, evens skin tone and reduces pigmentation. Perfect for tired, dull skin.",
      descAr: "علاج بفيتامين C يمنح الإشراقة ويوحد لون البشرة ويقلل التصبغات. مثالي للبشرة المتعبة والباهتة." },
    { name: "FIRMPRO + Mesojun – Ansiktslyft & Fasthet", nameEn: "FIRMPRO + Mesojun – lift & firmness", nameAr: "FIRMPRO + Mesojun – شدّ ورفع الوجه",
      duration: "50–60 min", price: "1 500 kr",
      desc: "DMAE, Organiskt Silanol, Panthenol och hyaluronsyra som definierar ansiktsoval, lyfter och motverkar slapphet.",
      descEn: "DMAE, organic silanol, panthenol and hyaluronic acid that define the facial contour, lift and counteract sagging.",
      descAr: "DMAE وسيلانول عضوي وبانثينول وحمض الهيالورونيك لتحديد ملامح الوجه ورفعه ومقاومة الترهل." },
    { name: "COLLAGEN-HA PRO + Mesojun – Anti-Aging & Återfuktning", nameEn: "COLLAGEN-HA PRO + Mesojun – anti-ageing & hydration", nameAr: "COLLAGEN-HA PRO + Mesojun – مقاومة التجاعيد وترطيب",
      duration: "50–60 min", price: "1 500 kr",
      desc: "Marint kollagen och hyaluronsyra med Succinic Acid mot ålderstecken, för bättre elasticitet och djup återfuktning.",
      descEn: "Marine collagen and hyaluronic acid with succinic acid against signs of ageing, for better elasticity and deep hydration.",
      descAr: "كولاجين بحري وحمض هيالورونيك مع حمض السكسينيك لمقاومة علامات التقدم بالعمر وتحسين المرونة والترطيب العميق." },
    { name: "B-LEUA RELAX – Naturligt alternativ till botox", nameEn: "B-LEUA RELAX – natural botox alternative", nameAr: "B-LEUA RELAX – بديل طبيعي للبوتوكس",
      duration: "60 min", price: "1 800 kr",
      desc: "Naturlig uppstramning som minskar mimiska linjer utan att frysa ansiktsuttrycken. Stimulerar kollagen och elastin. 100% säker, ingen återhämtning.",
      descEn: "Natural tightening that softens expression lines without freezing your face. Stimulates collagen and elastin. 100% safe, no downtime.",
      descAr: "شدّ طبيعي يخفف خطوط التعابير دون تجميد ملامح الوجه. يحفز الكولاجين والإيلاستين. آمن 100% وبدون فترة تعافٍ." },
    { name: "Mesojun + Hyaluronsyra 3% + Microneedling – Fukt & Anti-Aging", nameEn: "Mesojun + hyaluronic acid 3% + microneedling – moisture & anti-ageing", nameAr: "Mesojun + هيالورونيك 3% + ميكرونيدلينغ – ترطيب ومقاومة التجاعيد",
      duration: "50–60 min", price: "1 800 kr",
      desc: "150 mg hyaluronsyra i tre molekylvikter med microneedling för djup återfuktning och minskade fina linjer.",
      descEn: "150 mg hyaluronic acid in three molecular weights with microneedling for deep hydration and fewer fine lines.",
      descAr: "150 ملغ حمض هيالورونيك بثلاثة أوزان جزيئية مع ميكرونيدلينغ لترطيب عميق وتقليل الخطوط الرفيعة." },
    { name: "Microneedling + TRANEX PRO – Hudtonsbalans & Lyster", nameEn: "Microneedling + TRANEX PRO – tone balance & glow", nameAr: "ميكرونيدلينغ + TRANEX PRO – توحيد اللون وإشراقة",
      duration: "50–60 min", price: "1 000 kr",
      desc: "Tranexamic Acid, Kojic Acid och C-vitamin med microneedling för jämnare hudton och reducerade pigmentfläckar.",
      descEn: "Tranexamic acid, kojic acid and vitamin C with microneedling for a more even tone and reduced pigmentation.",
      descAr: "حمض الترانيكساميك والكوجيك وفيتامين C مع ميكرونيدلينغ لتوحيد لون البشرة وتقليل البقع الصبغية." },
    { name: "Mesojun + TRANEX PRO + Microneedling – Hudtonsbalans & Lyster", nameEn: "Mesojun + TRANEX PRO + microneedling – tone balance & glow", nameAr: "Mesojun + TRANEX PRO + ميكرونيدلينغ – توحيد اللون وإشراقة",
      duration: "50–60 min", price: "1 800 kr",
      desc: "Förstärkt version av ovanstående med Mesojun för djupare hudföryngring och starkare effekt på pigmentfläckar.",
      descEn: "A boosted version of the above with Mesojun for deeper rejuvenation and a stronger effect on pigmentation.",
      descAr: "نسخة معزّزة من العلاج السابق مع Mesojun لتجديد أعمق وتأثير أقوى على التصبغات." },
    { name: "BRIGHTPRO + Mesojun + Microneedling – Revitalisering & Ljusare hud", nameEn: "BRIGHTPRO + Mesojun + microneedling – revitalising & brightening", nameAr: "BRIGHTPRO + Mesojun + ميكرونيدلينغ – تنشيط وتفتيح",
      duration: "50–60 min", price: "1 800 kr",
      desc: "Högkoncentrerat Glutathion med C-vitamin och hyaluronsyra. Ger strålande, jämnare hudton och stimulerar kollagen.",
      descEn: "Highly concentrated glutathione with vitamin C and hyaluronic acid. Gives a radiant, more even tone and stimulates collagen.",
      descAr: "جلوتاثيون عالي التركيز مع فيتامين C وحمض الهيالورونيك. يمنح لوناً مشرقاً وموحداً ويحفز الكولاجين." },
    { name: "BOOSTER PRO EXOSOMER – Glöd & Revitaliserad hud", nameEn: "BOOSTER PRO exosomes – glow & revitalised skin", nameAr: "BOOSTER PRO إكسوسومات – توهج وتنشيط البشرة",
      duration: "45–55 min", price: "1 500 kr",
      desc: "Djuprengöring och intensiv återfuktning med exosomer för maximal lyster, föryngring och jämn hudton.",
      descEn: "Deep cleansing and intense hydration with exosomes for maximum glow, rejuvenation and even tone.",
      descAr: "تنظيف عميق وترطيب مكثف بالإكسوسومات لأقصى درجات الإشراقة والتجدد وتوحيد اللون." },
    { name: "Mesojun + BIOPLAX PRO + Microneedling – DNA-Revitalisering", nameEn: "Mesojun + BIOPLAX PRO + microneedling – DNA revitalisation", nameAr: "Mesojun + BIOPLAX PRO + ميكرونيدلينغ – تجديد على مستوى الخلايا",
      duration: "50–60 min", price: "2 000 kr",
      desc: "DNA extraherat från laxrom med 13 vitaminer, 20 aminosyror och peptider. Djupgående revitalisering på cellnivå.",
      descEn: "DNA extracted from salmon roe with 13 vitamins, 20 amino acids and peptides. Deep revitalisation at cell level.",
      descAr: "DNA مستخلص من بيوض السلمون مع 13 فيتاميناً و20 حمضاً أمينياً وببتيدات. تجديد عميق على مستوى الخلايا." },
  ],
},
{
  id: "hifu-ansikte",
  name: "HIFU – Ansikte",
  nameEn: "HIFU – Face",
  nameAr: "هايفو – الوجه",
  icon: "🌟",
  treatments: [
    { name: "VMAX HIFU & RF – Hela ansiktet", nameEn: "VMAX HIFU & RF – full face", nameAr: "VMAX هايفو و RF – الوجه كامل",
      duration: "60 min", price: "1 999 kr",
      desc: "Senaste generationens hudföryngring. Stimulerar kollagenproduktionen upp till 4 gånger mer. Inga nålar, ingen smärta. Resultat 1–2 år.",
      descEn: "Latest-generation skin rejuvenation. Stimulates collagen production up to four times more. No needles, no pain. Results last 1–2 years.",
      descAr: "أحدث جيل من تجديد البشرة. يحفز إنتاج الكولاجين حتى 4 أضعاف. بدون إبر وبدون ألم. نتائج تدوم من سنة إلى سنتين." },
    { name: "HIFU – Hela ansiktet", nameEn: "HIFU – full face", nameAr: "هايفو – الوجه كامل",
      duration: "60 min", price: "3 500 kr",
      desc: "Djupverkande fokuserat ultraljud som minskar rynkor, lyfter och ger naturlig lyster. Mild värme, ingen kirurgi.",
      descEn: "Deep-acting focused ultrasound that reduces wrinkles, lifts and adds natural radiance. Gentle warmth, no surgery.",
      descAr: "موجات فوق صوتية مركزة عميقة تقلل التجاعيد وترفع الوجه وتمنح إشراقة طبيعية. حرارة لطيفة وبدون جراحة." },
    { name: "HIFU – Runt ögonen", nameEn: "HIFU – eye area", nameAr: "هايفو – محيط العينين",
      duration: "20 min", price: "1 200 kr",
      desc: "Skonsam HIFU för det känsliga ögonpartiet. Minskar fina linjer och ger spänst.",
      descEn: "Gentle HIFU for the delicate eye area. Reduces fine lines and restores bounce.",
      descAr: "هايفو لطيف لمنطقة العين الحساسة. يقلل الخطوط الرفيعة ويعيد المرونة." },
    { name: "HIFU för ansikte", nameEn: "HIFU facial treatment", nameAr: "جلسة هايفو للوجه",
      duration: "90 min", price: "1 800 kr",
      desc: "Djupverkande behandling som stimulerar kollagenproduktionen och ger ansiktet ett naturligt lyft.",
      descEn: "Deep-acting treatment that stimulates collagen production and gives the face a natural lift.",
      descAr: "علاج عميق يحفز إنتاج الكولاجين ويمنح الوجه رفعاً طبيعياً." },
  ],
},
{
  id: "ogon-lappar",
  name: "Ögon & Läppar",
  nameEn: "Eyes & Lips",
  nameAr: "العيون والشفاه",
  icon: "👁",
  treatments: [
    { name: "Mesoterapi Eye Lift – Kollagenboost", nameEn: "Mesotherapy eye lift – collagen boost", nameAr: "ميزوثيرابي لرفع محيط العين – تعزيز الكولاجين",
      duration: "45 min", price: "799 kr",
      desc: "Microneedling och mesoterapi runt ögonen med serum som imiterar botoxeffekten. Minskar fina linjer, påsar och mörka ringar.",
      descEn: "Microneedling and mesotherapy around the eyes with serums that mimic the botox effect. Reduces fine lines, puffiness and dark circles.",
      descAr: "ميكرونيدلينغ وميزوثيرابي حول العينين بسيروم يحاكي مفعول البوتوكس. يقلل الخطوط الرفيعة والانتفاخ والهالات السوداء.",
      note: "Rekommenderas som kur: 3–4 behandlingar.", noteEn: "Recommended as a course: 3–4 sessions.", noteAr: "يُنصح به كبرنامج: 3–4 جلسات." },
    { name: "Pigmentbehandling för ögonpartiet", nameEn: "Pigmentation treatment for the eye area", nameAr: "علاج تصبغات محيط العين",
      duration: "30 min", price: "900 kr",
      desc: "Mot pigmentfläckar, melasma och mörka ringar. Peeling, pigmenthämmande mask, C-vitaminserum och solskydd.",
      descEn: "For pigmentation, melasma and dark circles. Peeling, pigment-inhibiting mask, vitamin C serum and sun protection.",
      descAr: "لعلاج التصبغات والكلف والهالات السوداء: تقشير، قناع مثبط للصبغات، سيروم فيتامين C وواقٍ شمسي." },
    { name: "HIFU Ögonbehandling – Icke-kirurgiskt lyft", nameEn: "HIFU eye treatment – non-surgical lift", nameAr: "هايفو للعينين – رفع غير جراحي",
      duration: "30 min", price: "1 200 kr",
      desc: "Fokuserat ultraljud som lyfter och stramar upp huden runt ögonen utan nålar. Ingen återhämtningstid.",
      descEn: "Focused ultrasound that lifts and tightens the skin around the eyes without needles. No downtime.",
      descAr: "موجات فوق صوتية مركزة ترفع وتشد البشرة حول العينين بدون إبر وبدون فترة تعافٍ.",
      note: "Rekommenderas var 6:e månad.", noteEn: "Recommended every 6 months.", noteAr: "يُنصح بتكراره كل 6 أشهر." },
    { name: "PlasmaJet för ögonlyft med ultraljud och RF", nameEn: "PlasmaJet eye lift with ultrasound and RF", nameAr: "بلازما جيت لرفع الجفون مع موجات فوق صوتية و RF",
      duration: "60 min", price: "2 000 kr",
      desc: "Nålfri behandling mot hängande ögonlock, kråksparkar och slapp hud. Stimulerar naturlig kollagenproduktion.",
      descEn: "Needle-free treatment for drooping eyelids, crow's feet and lax skin. Stimulates natural collagen production.",
      descAr: "علاج بدون إبر للجفون المترهلة وتجاعيد حول العين والجلد المرتخي. يحفز إنتاج الكولاجين الطبيعي." },
    { name: "BB-Lips med Tint – Färg, fukt & glow", nameEn: "BB-Lips with tint – colour, moisture & glow", nameAr: "بي بي ليبس مع تنت – لون وترطيب وإشراقة",
      duration: "60 min", price: "700 kr",
      desc: "Microneedling med serum rikt på hyaluronsyra och naturliga pigment. Jämnar ut läpparnas färg, naturlig tint-effekt utan smink.",
      descEn: "Microneedling with serums rich in hyaluronic acid and natural pigments. Evens lip colour with a natural tint effect — no makeup needed.",
      descAr: "ميكرونيدلينغ بسيروم غني بحمض الهيالورونيك وصبغات طبيعية. يوحد لون الشفاه بتأثير تنت طبيعي بدون مكياج.",
      note: "Kur: 2–4 behandlingar.", noteEn: "Course: 2–4 sessions.", noteAr: "برنامج: 2–4 جلسات." },
    { name: "Microneedling Lips med Mesoterapi", nameEn: "Lip microneedling with mesotherapy", nameAr: "ميكرونيدلينغ الشفاه مع ميزوثيرابي",
      duration: "45 min", price: "800 kr",
      desc: "Återfuktar och förbättrar läpparnas struktur och färg med microneedling och mesoterapiserum. Utan fillers.",
      descEn: "Hydrates and improves lip texture and colour with microneedling and mesotherapy serums. No fillers.",
      descAr: "يرطب ويحسّن ملمس الشفاه ولونها بالميكرونيدلينغ وسيروم الميزوثيرابي. بدون فيلر." },
    { name: "LIPS SHINE PRO – Volym & Lyster", nameEn: "LIPS SHINE PRO – volume & shine", nameAr: "LIPS SHINE PRO – امتلاء ولمعان",
      duration: "30–40 min", price: "1 000 kr",
      desc: "Hyaluronsyra och aktiva peptider för ökad volym, mjukare linjer runt munnen och naturlig färg med Ginkgo Biloba.",
      descEn: "Hyaluronic acid and active peptides for more volume, softer lines around the mouth and natural colour with ginkgo biloba.",
      descAr: "حمض هيالورونيك وببتيدات فعالة لامتلاء أكبر وخطوط أنعم حول الفم ولون طبيعي مع الجنكة." },
    { name: "HydraLips – Lyxbehandling", nameEn: "HydraLips – luxury treatment", nameAr: "هيدراليبس – العلاج الفاخر",
      duration: "60 min", price: "1 200 kr",
      desc: "Fysisk + kemisk peeling, HydraNeedling, mesoterapi med hyaluronsyra och vitaminer, lugnande mask och återfuktande balm.",
      descEn: "Physical + chemical peeling, HydraNeedling, mesotherapy with hyaluronic acid and vitamins, soothing mask and hydrating balm.",
      descAr: "تقشير فيزيائي وكيميائي، هيدرانيدلينغ، ميزوثيرابي بحمض الهيالورونيك والفيتامينات، قناع مهدئ وبلسم مرطب." },
  ],
},
{
  id: "harvard",
  name: "Hårvård",
  nameEn: "Hair care",
  nameAr: "العناية بالشعر",
  icon: "💇‍♀️",
  treatments: [
    { name: "Hår Microneedling (Mesoterapi)", nameEn: "Scalp microneedling (mesotherapy)", nameAr: "ميكرونيدلينغ فروة الرأس (ميزوثيرابي)",
      duration: "60 min", price: "1 000 kr",
      desc: "Stärker hårsäckarna och stimulerar ny hårväxt med microneedling, exosomer, high frequency och LED-terapi.",
      descEn: "Strengthens hair follicles and stimulates new growth with microneedling, exosomes, high frequency and LED therapy.",
      descAr: "يقوي بصيلات الشعر ويحفز نمواً جديداً بالميكرونيدلينغ والإكسوسومات والتردد العالي وعلاج LED." },
    { name: "Mesojun + HAIRPRO Exosomes – Hårrevitalisering", nameEn: "Mesojun + HAIRPRO exosomes – hair revitalisation", nameAr: "Mesojun + HAIRPRO إكسوسومات – تنشيط الشعر",
      duration: "40–50 min", price: "1 000 kr",
      desc: "5,49 miljoner stabila exosomer med Ginkgo Biloba och peptider. Stimulerar hårbotten, motverkar håravfall.",
      descEn: "5.49 million stable exosomes with ginkgo biloba and peptides. Stimulates the scalp and counteracts hair loss.",
      descAr: "5.49 مليون إكسوسوم ثابت مع الجنكة والببتيدات. يحفز فروة الرأس ويقاوم تساقط الشعر." },
    { name: "Lyxig hår- och hårbottenbehandling", nameEn: "Luxury hair & scalp treatment", nameAr: "علاج فاخر للشعر وفروة الرأس",
      duration: "60 min", price: "1 800 kr",
      desc: "Hydro-dermabrasion, DNA Salmon-spray, exosomer, hyaluronsyra, radiofrekvens och högfrekvenskam för friskare hårväxt.",
      descEn: "Hydro-dermabrasion, DNA Salmon spray, exosomes, hyaluronic acid, radio frequency and a high-frequency comb for healthier hair growth.",
      descAr: "هيدرو-ديرمابريجن، بخاخ DNA Salmon، إكسوسومات، حمض هيالورونيك، تردد راديوي ومشط تردد عالٍ لنمو شعر أكثر صحة." },
  ],
},
{
  id: "massage-ansikte",
  name: "Massage – Ansikte",
  nameEn: "Massage – Face",
  nameAr: "مساج – الوجه",
  icon: "🤍",
  note: "Endast för kvinnor",
  noteEn: "Women only",
  noteAr: "للنساء فقط",
  treatments: [
    { name: "Ansiktsmassage", nameEn: "Facial massage", nameAr: "مساج الوجه",
      duration: "30 min", price: "700 kr",
      desc: "Mjuk, rogivande massage fokuserad på ansiktet. Löser spänningar och hjälper mot spänningshuvudvärk.",
      descEn: "Soft, calming massage focused on the face. Releases tension and helps with tension headaches.",
      descAr: "مساج ناعم ومهدئ للوجه. يفك التوتر ويساعد على تخفيف صداع التوتر.",
      note: "Endast för kvinnor.", noteEn: "Women only.", noteAr: "للنساء فقط." },
    { name: "Ansiktsmassage / Akupressurmassage", nameEn: "Facial / acupressure massage", nameAr: "مساج الوجه / مساج بالضغط",
      duration: "30 min", price: "850 kr",
      desc: "Djupgående fasciamassage med lyftande och cirkulationsökande tekniker, anpassad efter behov.",
      descEn: "Deep fascia massage with lifting, circulation-boosting techniques, adapted to your needs.",
      descAr: "مساج عميق للفاشيا بتقنيات رافعة ومنشطة للدورة الدموية، حسب احتياجك.",
      note: "Endast för kvinnor.", noteEn: "Women only.", noteAr: "للنساء فقط." },
    { name: "Ansikts- & Nackmassage", nameEn: "Face & neck massage", nameAr: "مساج الوجه والرقبة",
      duration: "60 min", price: "1 500 kr",
      desc: "Ansikts- och nackmassage med massage av dekolletage, axlar, armar och händer. Stramar upp och löser djupa spänningar.",
      descEn: "Face and neck massage including décolletage, shoulders, arms and hands. Tightens and releases deep tension.",
      descAr: "مساج للوجه والرقبة يشمل الصدر والكتفين والذراعين واليدين. يشد البشرة ويفك التوتر العميق.",
      note: "Endast för kvinnor.", noteEn: "Women only.", noteAr: "للنساء فقط." },
    { name: "Ansikts-, Skalp- & Dekolletagemassage", nameEn: "Face, scalp & décolletage massage", nameAr: "مساج الوجه وفروة الرأس والصدر",
      duration: "30 min", price: "700 kr",
      desc: "Klassisk massage av ansikte, skalp, nacke och dekolletage. Energigivande paus under dagen.",
      descEn: "Classic massage of face, scalp, neck and décolletage. An energising break in your day.",
      descAr: "مساج كلاسيكي للوجه وفروة الرأس والرقبة والصدر. استراحة منعشة خلال يومك.",
      note: "Endast för kvinnor. Kur 3 behandlingar: 1 450 kr.", noteEn: "Women only. Course of 3: 1 450 kr.", noteAr: "للنساء فقط. برنامج 3 جلسات: 1 450 كرون." },
    { name: "Ansikts-, Skalp- & Dekolletagemassage – Paket 5 behandlingar", nameEn: "Face, scalp & décolletage massage – package of 5", nameAr: "مساج الوجه وفروة الرأس والصدر – باقة 5 جلسات",
      duration: "120 min/tillfälle", price: "1 950 kr",
      desc: "Total avslappning med omsorgsfull massage av ansikte, skalp, nacke och dekolletage.",
      descEn: "Total relaxation with attentive massage of face, scalp, neck and décolletage.",
      descAr: "استرخاء تام مع مساج عناية للوجه وفروة الرأس والرقبة والصدر.",
      note: "Endast för kvinnor.", noteEn: "Women only.", noteAr: "للنساء فقط." },
    { name: "Ansiktsbehandling inkl. 15 min ryggmassage", nameEn: "Facial incl. 15 min back massage", nameAr: "علاج للوجه مع 15 دقيقة مساج للظهر",
      duration: "30 min", price: "1 299 kr",
      desc: "Ryggmassage mot spända muskler med NBE-maskin, följt av grundläggande ansiktsbehandling med hudanalys, peeling och serum.",
      descEn: "Back massage for tense muscles with the NBE machine, followed by a basic facial with skin analysis, peeling and serum.",
      descAr: "مساج للظهر لفك تشنج العضلات بجهاز NBE، يليه علاج أساسي للوجه مع تحليل للبشرة وتقشير وسيروم.",
      note: "Tillval (portömning, fransfärg m.m.) anges vid bokning.", noteEn: "Add-ons (extraction, lash tint etc.) specified at booking.", noteAr: "الإضافات (تنظيف مسام، صبغ رموش وغيرها) تُحدد عند الحجز." },
  ],
},
{
  id: "massage-kropp",
  name: "Massage – Kropp",
  nameEn: "Massage – Body",
  nameAr: "مساج – الجسم",
  icon: "💆‍♀️",
  treatments: [
    { name: "Avslappningsmassage", nameEn: "Relaxation massage", nameAr: "مساج استرخاء",
      duration: "30 min", price: "från 900 kr", priceEn: "from 900 kr", priceAr: "ابتداءً من 900 كرون",
      desc: "Skonsam, lugnande massage för hela kroppen.",
      descEn: "Gentle, calming massage for the whole body.",
      descAr: "مساج لطيف ومهدئ لكامل الجسم." },
    { name: "Klassisk svensk massage", nameEn: "Classic Swedish massage", nameAr: "المساج السويدي الكلاسيكي",
      duration: "30 min", price: "1 000 kr",
      desc: "Traditionell svensk massageteknik mot spänningar i kroppen.",
      descEn: "Traditional Swedish massage technique for tension in the body.",
      descAr: "تقنية المساج السويدي التقليدية لعلاج توتر عضلات الجسم." },
    { name: "Rygg & Nacke", nameEn: "Back & neck", nameAr: "الظهر والرقبة",
      duration: "30 min", price: "999 kr",
      desc: "Fokuserad massage på rygg och nacke.",
      descEn: "Focused massage of the back and neck.",
      descAr: "مساج مركز على الظهر والرقبة." },
    { name: "Ryggmassage med radiofrekvens (NBE 3000)", nameEn: "Back massage with radio frequency (NBE 3000)", nameAr: "مساج الظهر بالتردد الراديوي (NBE 3000)",
      duration: "30 min", price: "999 kr",
      desc: "20 min med NBE 3000-maskin som löser upp spända vävnader och myoser, följt av 10 min handmassage.",
      descEn: "20 min with the NBE 3000 machine to release tight tissue and knots, followed by 10 min of hands-on massage.",
      descAr: "20 دقيقة بجهاز NBE 3000 لفك الأنسجة المشدودة والعقد العضلية، تليها 10 دقائق مساج يدوي." },
    { name: "Dekolletémassage", nameEn: "Décolletage massage", nameAr: "مساج منطقة الصدر",
      duration: "20 min", price: "700 kr",
      desc: "Riktad massage för dekolletageområdet.",
      descEn: "Targeted massage for the décolletage area.",
      descAr: "مساج موجه لمنطقة الصدر والعنق." },
    { name: "Lätt lymfmassage", nameEn: "Light lymphatic massage", nameAr: "مساج لمفاوي خفيف",
      duration: "30 min", price: "1 100 kr",
      desc: "Skonsam lymfdränerande massage som minskar svullnad och stimulerar cirkulationen.",
      descEn: "Gentle lymphatic drainage massage that reduces swelling and stimulates circulation.",
      descAr: "مساج لطيف لتصريف اللمف يقلل التورم وينشط الدورة الدموية." },
    { name: "Helkroppsmassage", nameEn: "Full-body massage", nameAr: "مساج كامل الجسم",
      duration: "45 min", price: "1 800 kr",
      desc: "Komplett massage för hela kroppen.",
      descEn: "Complete massage for the whole body.",
      descAr: "مساج متكامل لكامل الجسم." },
  ],
},
{
  id: "kroppsbehandlingar",
  name: "Kroppsbehandlingar",
  nameEn: "Body treatments",
  nameAr: "علاجات الجسم",
  icon: "🧴",
  treatments: [
    { name: "Ryggbehandling mot akne", nameEn: "Back treatment for acne", nameAr: "علاج حب الشباب في الظهر",
      duration: "60 min", price: "1 000 kr",
      desc: "Antibakteriell rengöring, kemisk peeling, diamantslipning, oxygenbehandling och lermask. Lugnar inflammationer.",
      descEn: "Antibacterial cleansing, chemical peel, diamond peeling, oxygen treatment and clay mask. Calms inflammation.",
      descAr: "تنظيف مضاد للبكتيريا، تقشير كيميائي وماسي، علاج بالأوكسجين وقناع طيني. يهدئ الالتهابات." },
    { name: "Behandling för knän", nameEn: "Knee treatment", nameAr: "علاج منطقة الركبتين",
      duration: "45 min", price: "1 000 kr",
      desc: "Rengöring, peeling, diamantslipning, oxygenbehandling och mask för mörka eller ojämna knän.",
      descEn: "Cleansing, peeling, diamond peeling, oxygen treatment and mask for dark or uneven knees.",
      descAr: "تنظيف وتقشير عادي وماسي وعلاج بالأوكسجين وقناع لاسمرار الركبتين أو تفاوت لونهما." },
    { name: "Behandling för ben – lyster & jämnare hudton", nameEn: "Leg treatment – glow & more even tone", nameAr: "علاج الساقين – إشراقة وتوحيد اللون",
      duration: "60 min", price: "1 000 kr",
      desc: "Exfoliering, återfuktning och hudtonsutjämning för benens hud.",
      descEn: "Exfoliation, hydration and tone-evening for the skin on your legs.",
      descAr: "تقشير وترطيب وتوحيد لون بشرة الساقين." },
    { name: "Behandling för armhålor", nameEn: "Underarm treatment", nameAr: "علاج منطقة الإبطين",
      duration: "45 min", price: "1 000 kr",
      desc: "Lugnar och ljusar upp mörka eller irriterade armhålor.",
      descEn: "Calms and brightens dark or irritated underarms.",
      descAr: "يهدئ ويفتح لون الإبطين الداكنين أو المتهيجين." },
    { name: "Behandling för armar och händer", nameEn: "Arm & hand treatment", nameAr: "علاج الذراعين واليدين",
      duration: "45 min", price: "1 000 kr",
      desc: "Skonsam behandling för torra, mörka eller fläckiga armar och händer.",
      descEn: "Gentle treatment for dry, dark or blotchy arms and hands.",
      descAr: "علاج لطيف للذراعين واليدين الجافة أو الداكنة أو المبقعة." },
    { name: "Lyxbehandling för händer – Microneedling & Mesoterapi", nameEn: "Luxury hand treatment – microneedling & mesotherapy", nameAr: "علاج فاخر لليدين – ميكرونيدلينغ وميزوثيرابي",
      duration: "60 min", price: "1 200 kr",
      desc: "Peeling, diamantslipning, oxygenbehandling, microneedling och mesoterapi (Kollagen + DNA Salmon). Synlig glow.",
      descEn: "Peeling, diamond peeling, oxygen treatment, microneedling and mesotherapy (collagen + DNA Salmon). Visible glow.",
      descAr: "تقشير عادي وماسي، علاج بالأوكسجين، ميكرونيدلينغ وميزوثيرابي (كولاجين + DNA Salmon). توهج ملحوظ." },
  ],
},
{
  id: "slim-firm",
  name: "Slim & Firm – Kroppsformning",
  nameEn: "Slim & Firm – Body contouring",
  nameAr: "شدّ ونحت الجسم",
  icon: "🔥",
  treatments: [
    { name: "Mesoterapi för magen", nameEn: "Mesotherapy – stomach", nameAr: "ميزوثيرابي للبطن",
      duration: "60 min", price: "2 000 kr",
      desc: "Förbättrar hudens fasthet och minskar fettansamlingar med microneedling, mesoterapi, ultraljud och RF.",
      descEn: "Improves skin firmness and reduces fat deposits with microneedling, mesotherapy, ultrasound and RF.",
      descAr: "يحسّن شدّ البشرة ويقلل تراكم الدهون بالميكرونيدلينغ والميزوثيرابي والموجات فوق الصوتية وRF." },
    { name: "Mesoterapi för midja & höfter (love handles)", nameEn: "Mesotherapy – waist & hips (love handles)", nameAr: "ميزوثيرابي للخصر والوركين",
      duration: "60 min", price: "2 500 kr",
      desc: "Formar midjan och reducerar fettdepåer på sidorna med fettbrytande serum och lymfdränerande massage.",
      descEn: "Shapes the waist and reduces fat pockets at the sides with fat-dissolving serums and lymphatic massage.",
      descAr: "ينحت الخصر ويقلل دهون الجوانب بسيرومات مذيبة للدهون ومساج لمفاوي." },
    { name: "Mesoterapi för rumpa & lår", nameEn: "Mesotherapy – buttocks & thighs", nameAr: "ميزوثيرابي للأرداف والفخذين",
      duration: "60 min", price: "2 500 kr",
      desc: "Minskar celluliter och förbättrar hudens spänst med microneedling, mesoterapi, ultraljud och RF.",
      descEn: "Reduces cellulite and improves skin elasticity with microneedling, mesotherapy, ultrasound and RF.",
      descAr: "يقلل السيلوليت ويحسّن مرونة البشرة بالميكرونيدلينغ والميزوثيرابي والموجات فوق الصوتية وRF." },
    { name: "Mesoterapi för armar (överarmar)", nameEn: "Mesotherapy – upper arms", nameAr: "ميزوثيرابي لأعلى الذراعين",
      duration: "45–60 min", price: "2 000 kr",
      desc: "Reducerar fett och slapp hud på överarmarna med fettlösande mesoterapi och RF.",
      descEn: "Reduces fat and lax skin on the upper arms with fat-dissolving mesotherapy and RF.",
      descAr: "يقلل الدهون والترهل في أعلى الذراعين بميزوثيرابي مذيب للدهون وRF." },
    { name: "Mesoterapi för dubbelhaka och käklinje", nameEn: "Mesotherapy – double chin & jawline", nameAr: "ميزوثيرابي للذقن المزدوج وخط الفك",
      duration: "45 min", price: "1 500 kr",
      desc: "Minskar fett under hakan och stramar upp huden med fettlösande mesoterapi, RF och lätt massage.",
      descEn: "Reduces fat under the chin and tightens the skin with fat-dissolving mesotherapy, RF and light massage.",
      descAr: "يقلل الدهون تحت الذقن ويشد البشرة بميزوثيرابي مذيب للدهون وRF ومساج خفيف." },
  ],
},
{
  id: "bristningar",
  name: "Bristningsbehandling",
  nameEn: "Stretch mark treatments",
  nameAr: "علاج علامات التمدد",
  icon: "🌿",
  treatments: [
    { name: "Mesoterapi mot bristningar – Mage", nameEn: "Mesotherapy for stretch marks – stomach", nameAr: "ميزوثيرابي لعلامات التمدد – البطن",
      duration: "60 min", price: "1 099 kr",
      desc: "Minskar synligheten av bristningar på magen, särskilt efter graviditet eller viktförändringar.",
      descEn: "Reduces the visibility of stretch marks on the stomach, especially after pregnancy or weight changes.",
      descAr: "يقلل ظهور علامات التمدد على البطن، خاصة بعد الحمل أو تغيرات الوزن." },
    { name: "Mesoterapi mot bristningar – Höfter & Lår", nameEn: "Mesotherapy for stretch marks – hips & thighs", nameAr: "ميزوثيرابي لعلامات التمدد – الوركان والفخذان",
      duration: "60 min", price: "1 099 kr",
      desc: "Minskar bristningar och förbättrar hudens ton, struktur och fasthet på höfter och lår.",
      descEn: "Reduces stretch marks and improves skin tone, texture and firmness on hips and thighs.",
      descAr: "يقلل علامات التمدد ويحسّن لون البشرة وملمسها وشدّها في الوركين والفخذين." },
    { name: "Mesoterapi mot bristningar – Armar", nameEn: "Mesotherapy for stretch marks – arms", nameAr: "ميزوثيرابي لعلامات التمدد – الذراعان",
      duration: "45 min", price: "1 099 kr",
      desc: "Förbättrar hudstrukturen och reducerar bristningar på överarmarna.",
      descEn: "Improves skin texture and reduces stretch marks on the upper arms.",
      descAr: "يحسّن ملمس البشرة ويقلل علامات التمدد في أعلى الذراعين." },
    { name: "Mesoterapi mot bristningar – Bröstområde", nameEn: "Mesotherapy for stretch marks – chest area", nameAr: "ميزوثيرابي لعلامات التمدد – منطقة الصدر",
      duration: "45 min", price: "1 099 kr",
      desc: "Skonsam behandling för bristningar på bröstet, särskilt efter amning eller viktförändringar.",
      descEn: "Gentle treatment for stretch marks on the chest, especially after breastfeeding or weight changes.",
      descAr: "علاج لطيف لعلامات التمدد في الصدر، خاصة بعد الرضاعة أو تغيرات الوزن." },
    { name: "Laser – Stretch Marks (Mage)", nameEn: "Laser – stretch marks (stomach)", nameAr: "ليزر – علامات التمدد (البطن)",
      duration: "45 min", price: "1 800 kr",
      desc: "Laserbehandling som stimulerar kollagenproduktionen. Passar både nya (röda) och äldre (vita) bristningar.",
      descEn: "Laser treatment that stimulates collagen production. Suits both new (red) and older (white) stretch marks.",
      descAr: "علاج ليزر يحفز إنتاج الكولاجين. مناسب لعلامات التمدد الجديدة (الحمراء) والقديمة (البيضاء)." },
  ],
},
{
  id: "hifu-kropp",
  name: "HIFU – Kropp",
  nameEn: "HIFU – Body",
  nameAr: "هايفو – الجسم",
  icon: "💫",
  treatments: [
    { name: "HIFU – Haklinje (dubbelhaka)", nameEn: "HIFU – jawline (double chin)", nameAr: "هايفو – خط الفك (الذقن المزدوج)",
      duration: "30 min", price: "1 500 kr",
      desc: "Stramar upp huden under hakan och minskar dubbelhaka.",
      descEn: "Tightens the skin under the chin and reduces double chin.",
      descAr: "يشد البشرة تحت الذقن ويقلل الذقن المزدوج." },
    { name: "HIFU – Dekolletage", nameEn: "HIFU – décolletage", nameAr: "هايفو – منطقة الصدر",
      duration: "40 min", price: "2 000 kr",
      desc: "Förbättrar hudens fasthet och struktur i bröstområdet.",
      descEn: "Improves skin firmness and texture in the chest area.",
      descAr: "يحسّن شدّ البشرة وملمسها في منطقة الصدر." },
    { name: "HIFU – Armar (överarmar)", nameEn: "HIFU – upper arms", nameAr: "هايفو – أعلى الذراعين",
      duration: "30 min", price: "2 500 kr",
      desc: "Stärker huden på överarmarna och reducerar slapphet.",
      descEn: "Firms the skin on the upper arms and reduces laxity.",
      descAr: "يقوي بشرة أعلى الذراعين ويقلل الترهل." },
    { name: "HIFU – Lår", nameEn: "HIFU – thighs", nameAr: "هايفو – الفخذان",
      duration: "45 min", price: "2 500 kr",
      desc: "Stramar upp huden på låren och reducerar slapphet.",
      descEn: "Tightens the skin on the thighs and reduces laxity.",
      descAr: "يشد بشرة الفخذين ويقلل الترهل." },
    { name: "HIFU – Mage", nameEn: "HIFU – stomach", nameAr: "هايفو – البطن",
      duration: "45 min", price: "2 500 kr",
      desc: "Stramar upp huden på magen, särskilt efter viktminskning eller graviditet.",
      descEn: "Tightens the skin on the stomach, especially after weight loss or pregnancy.",
      descAr: "يشد بشرة البطن، خاصة بعد فقدان الوزن أو الحمل." },
  ],
},
{
  id: "laser",
  name: "Laser",
  nameEn: "Laser",
  nameAr: "الليزر",
  icon: "⚡",
  treatments: [
    { name: "Pico Laser + Djupgående rengöring & peeling", nameEn: "Pico laser + deep cleansing & peeling", nameAr: "بيكو ليزر + تنظيف عميق وتقشير",
      duration: "60–75 min", price: "2 000 kr",
      desc: "HydraFacial/Oxygeneo + Diamond Peel för rengöring, följt av Pico Laser mot pigmentering, ytliga ärr och kollagenstimulering.",
      descEn: "HydraFacial/Oxygeneo + diamond peel for cleansing, followed by pico laser for pigmentation, superficial scars and collagen stimulation.",
      descAr: "هيدرافيشل/أوكسجينيو مع تقشير ماسي للتنظيف، يليه بيكو ليزر للتصبغات والندبات السطحية وتحفيز الكولاجين." },
    { name: "Laser Carbon + HydraFacial + Lugnande mask", nameEn: "Carbon laser + HydraFacial + soothing mask", nameAr: "ليزر الكربون + هيدرافيشل + قناع مهدئ",
      duration: "60 min", price: "2 000 kr",
      desc: "Laser Carbon djuprengör porer och minskar pigmentering. HydraFacial återfuktar. Perfekt för fet hud och stora porer.",
      descEn: "Carbon laser deep-cleans pores and reduces pigmentation. HydraFacial hydrates. Perfect for oily skin and enlarged pores.",
      descAr: "ليزر الكربون ينظف المسام بعمق ويقلل التصبغات، والهيدرافيشل يرطب. مثالي للبشرة الدهنية والمسام الواسعة." },
    { name: "Laser – Borttagning av tatuering", nameEn: "Laser tattoo removal", nameAr: "إزالة الوشم بالليزر",
      duration: "20–40 min", price: "från 800 kr", priceEn: "from 800 kr", priceAr: "ابتداءً من 800 كرون",
      desc: "Lasern bryter ner bläckpartiklarna gradvis. Antal behandlingar varierar med storlek, placering och färg.",
      descEn: "The laser gradually breaks down ink particles. The number of sessions varies with size, placement and colour.",
      descAr: "الليزر يفكك جزيئات الحبر تدريجياً. عدد الجلسات يعتمد على الحجم والموقع واللون." },
    { name: "Laser – Borttagning av tatuering (läppar/ögonbryn)", nameEn: "Laser tattoo removal (lips/brows)", nameAr: "إزالة تاتو الشفاه/الحواجب بالليزر",
      duration: "15–30 min", price: "800 kr",
      desc: "Specialiserad, precis behandling för känsliga områden. Gradvis och naturlig blekning.",
      descEn: "Specialised, precise treatment for sensitive areas. Gradual, natural fading.",
      descAr: "علاج دقيق ومتخصص للمناطق الحساسة. تفتيح تدريجي وطبيعي." },
  ],
},
{
  id: "plasma",
  name: "Plasma",
  nameEn: "Plasma",
  nameAr: "البلازما",
  icon: "🩵",
  treatments: [
    { name: "Plasma Radiance – Full Facial Treatment", nameEn: "Plasma Radiance – full facial treatment", nameAr: "بلازما رادينس – علاج كامل للوجه",
      duration: "65 min", price: "1 200 kr",
      desc: "Rengöring, PlasmaPen med vitaminserum (BSK29), LED-ljusterapi och återfuktande mask. Lyster utan irritation.",
      descEn: "Cleansing, PlasmaPen with vitamin serum (BSK29), LED light therapy and a hydrating mask. Radiance without irritation.",
      descAr: "تنظيف، قلم بلازما مع سيروم فيتامينات (BSK29)، علاج بضوء LED وقناع مرطب. إشراقة بدون تهيج.",
      note: "Upprepas var 3–4 vecka.", noteEn: "Repeat every 3–4 weeks.", noteAr: "يُكرر كل 3–4 أسابيع." },
    { name: "PlasmaJet – Hela ansiktet", nameEn: "PlasmaJet – full face", nameAr: "بلازما جيت – الوجه كامل",
      duration: "60 min", price: "3 000 kr",
      desc: "Mikroskopiska punkter som stimulerar naturlig kollagenproduktion och ger ett synligt lyft.",
      descEn: "Microscopic points that stimulate natural collagen production and give a visible lift.",
      descAr: "نقاط ميكروسكوبية تحفز إنتاج الكولاجين الطبيعي وتمنح رفعاً ملحوظاً." },
    { name: "Borttagning av skin tags med Plasma Pen", nameEn: "Skin tag removal with plasma pen", nameAr: "إزالة الزوائد الجلدية بقلم البلازما",
      duration: "15–30 min", price: "från 1 500 kr", priceEn: "from 1 500 kr", priceAr: "ابتداءً من 1 500 كرون",
      desc: "Nålfri borttagning av hudutväxter (fibrom) på hals, ansikte, armhålor eller kropp.",
      descEn: "Needle-free removal of skin tags (fibromas) on the neck, face, underarms or body.",
      descAr: "إزالة الزوائد الجلدية (الفيبروما) من الرقبة أو الوجه أو الإبطين أو الجسم بدون إبر.",
      note: "Konsultation krävs innan bokning.", noteEn: "Consultation required before booking.", noteAr: "تلزم استشارة قبل الحجز." },
  ],
},
{
  id: "arrbehandling",
  name: "Ärrbehandling",
  nameEn: "Scar treatments",
  nameAr: "علاج الندبات",
  icon: "🌸",
  treatments: [
    { name: "SCARPRO + Mesojun – Hudreparation", nameEn: "SCARPRO + Mesojun – skin repair", nameAr: "SCARPRO + Mesojun – إصلاح البشرة",
      duration: "50–60 min", price: "1 500 kr",
      desc: "Stimulerar hudförnyelse, förbättrar hudstruktur och minskar synligheten av akneärr.",
      descEn: "Stimulates skin renewal, improves texture and reduces the visibility of acne scars.",
      descAr: "يحفز تجدد البشرة ويحسّن ملمسها ويقلل ظهور ندبات حب الشباب." },
    { name: "SCARPRO + Mesojun + Microneedling – Komplett ärrbehandling", nameEn: "SCARPRO + Mesojun + microneedling – complete scar treatment", nameAr: "SCARPRO + Mesojun + ميكرونيدلينغ – علاج متكامل للندبات",
      duration: "60–70 min", price: "1 800 kr",
      desc: "Djupare behandling med microneedling för starkare kollagenstimulering och bättre ärrminskning.",
      descEn: "A deeper treatment with microneedling for stronger collagen stimulation and better scar reduction.",
      descAr: "علاج أعمق مع الميكرونيدلينغ لتحفيز أقوى للكولاجين ونتائج أفضل على الندبات." },
    { name: "Algpeeling", nameEn: "Algae peeling", nameAr: "تقشير الطحالب",
      duration: "45 min", price: "1 800 kr",
      desc: "Naturlig peeling med mikroskopiska algspikler som aktiverar cellförnyelse. Förfinade porer, förbättrade akneärr.",
      descEn: "Natural peeling with microscopic algae spicules that activate cell renewal. Refined pores, improved acne scars.",
      descAr: "تقشير طبيعي بإبر الطحالب الميكروسكوبية ينشط تجدد الخلايا. مسام أدق وندبات حب شباب أفضل." },
  ],
},
{
  id: "ovrigt",
  name: "Övrigt",
  nameEn: "Other",
  nameAr: "خدمات أخرى",
  icon: "🕊",
  treatments: [
    { name: "Hudvårdskonsultation", nameEn: "Skin consultation", nameAr: "استشارة العناية بالبشرة",
      duration: "20 min", price: "450 kr",
      desc: "Personlig hudanalys för att hitta rätt behandling för din hudtyp.",
      descEn: "A personal skin analysis to find the right treatment for your skin type.",
      descAr: "تحليل شخصي للبشرة لإيجاد العلاج الأنسب لنوع بشرتك." },
  ],
},
];

/* Hjälpare för språkversioner */
function nssLang() {
  var l = document.documentElement.lang || "sv";
  return l.indexOf("ar") === 0 ? "ar" : l.indexOf("en") === 0 ? "en" : "sv";
}
function tName(o){ var l=nssLang(); return (l==="en"&&o.nameEn)||(l==="ar"&&o.nameAr)||o.name; }
function tDesc(o){ var l=nssLang(); return (l==="en"&&o.descEn)||(l==="ar"&&o.descAr)||o.desc; }
function tNote(o){ var l=nssLang(); return (l==="en"&&o.noteEn)||(l==="ar"&&o.noteAr)||o.note; }
function tPrice(o){ var l=nssLang(); return (l==="en"&&o.priceEn)||(l==="ar"&&o.priceAr)||o.price; }
